name: blackhole
description: An Open Source Music Player App.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  app_links: ^6.4.0
  audio_service: ^0.18.12
  audiotagger: ^2.2.1
  # bitsdojo_window: ^0.1.1+1 #For Desktops
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.6
  dart_des: ^1.0.2
  device_info_plus: ^11.3.0
  file_picker: ^9.0.2
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_archive: ^6.0.0
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_lyric: ^2.0.4+6
  get_it: ^7.6.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html_unescape: ^2.0.0
  just_audio: ^0.9.36
  logging: ^1.2.0
  marquee: ^2.2.3
  material_design_icons_flutter: 5.0.5955-rc.1
  media_store_plus: ^0.1.3
  metadata_god: ^1.0.0
  on_audio_query: ^2.9.0
  package_info_plus: ^8.3.0
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  persistent_bottom_nav_bar: ^6.2.1
  receive_sharing_intent: ^1.6.7
  share_plus: ^10.1.4
  sizer: ^2.0.15
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.2.4
  uuid: ^4.5.1
  win32: ^5.5.3
  youtube_explode_dart: ^2.1.0

dependency_overrides:
  fading_edge_scrollview: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  msix: ^3.16.7

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets to the application.
    - assets/

msix_config:
  display_name: BlackHole
  publisher_display_name: Ankit Sangwan
  identity_name: com.shadow.blackhole
  icons_background_color: transparent
  logo_path: assets/ic_launcher.png
  file_extension: .mp3, .m4a
